name: CI
on:
  push:
    branches: [ test-clickable-widget ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  package:
    needs: [ lint ]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: memorize-phrase.apk
          path: app/build/outputs/apk/debug/app-debug.apk